version: '3'
services:
  webui:
    build: 
      context: webui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  webapi:
    build: 
      context: webapi
      dockerfile: Dockerfile
    ports:
      - "8081:80"
  sql:
    image: "microsoft/mssql-server-windows-developer"
    environment:
      - sa_password=P@ssw0rd!
      - ACCEPT_EULA=Y 
    ports:
      - "1433:1433"